# Multipass VMs
[jenkins_master]
worker1 ansible_host=10.158.148.119 ansible_user=ubuntu ansible_ssh_private_key_file=../multipass/ssh-keys/multipass_key

[k3s_control_plane]
worker2 ansible_host=10.158.148.130 ansible_user=ubuntu ansible_ssh_private_key_file=../multipass/ssh-keys/multipass_key

[k3s_workers]
worker3 ansible_host=10.158.148.234 ansible_user=ubuntu ansible_ssh_private_key_file=../multipass/ssh-keys/multipass_key
worker4 ansible_host=10.158.148.86 ansible_user=ubuntu ansible_ssh_private_key_file=../multipass/ssh-keys/multipass_key

[k3s_cluster:children]
k3s_control_plane
k3s_workers

[all_nodes:children]
jenkins_master
k3s_cluster

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
k3s_version=stable
