---
- name: "Controller: Main Task Flow"
  debug:
    msg: "Setting up Ansible Controller on {{ inventory_hostname }}"

- name: Include install_ansible tasks
  include_tasks: install_ansible.yml

- name: Include generate_ssh_keys tasks
  include_tasks: generate_ssh_keys.yml

- name: Include distribute_pubkey tasks
  include_tasks: distribute_pubkey.yml

- name: "Controller: Setup Complete"
  debug:
    msg: "Ansible installed | SSH keys generated | Ready for Stage2"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop:
    - { ip: "10.0.2.31", name: "worker1" }
    - { ip: "10.0.3.184", name: "worker2" }
    - { ip: "10.0.1.217", name: "worker3" }
    - { ip: "10.0.2.211", name: "worker4"}
  become: yes
