apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  labels:
    app: nginx
    assignment: "4"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: None
