# Run from control node
[control]
control-node ansible_host=10.0.2.216 ansible_user=ubuntu control_node=true  ansible_ssh_private_key_file=~/.ssh/control-key.pem

[jenkins]
jenkins-node ansible_host=10.0.3.225 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/jenkins-key.pem

[prod]
prod-node ansible_host=10.0.1.22 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/prod-key.pem

[test]
test-node ansible_host=10.0.2.184 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/test-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
jenkins_ip=10.0.3.225
test_ip=10.0.2.184
prod_ip=10.0.1.22
