---
- name: Install Java 21 (for Jenkins 2.528+)
  apt:
    name: openjdk-21-jre-headless
    state: present
  become: yes


- name: Set JAVA_HOME for Java 21
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
    regexp: '^JAVA_HOME='  # Replace existing line
  become: yes


- name: Add JAVA_HOME to profile
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64'
    regexp: '^export JAVA_HOME='  # Replace existing line
  become: yes
